let nombreDeSuperHeroe = 'Batman';
let nombre = 'Bruce Wayne';
let vuela = false;
let maneja = true;
let vida = 99;
let trabajo = undefined;
let tiempoLibre = null;

console.log('Nombre de Superheroe', nombreDeSuperHeroe);
console.log('Nombre de Superheroe', typeof nombreDeSuperHeroe);
console.log('Nombre', nombre);
console.log('Nombre', typeof nombre);
console.log('Vuela', vuela);
console.log('Vuela', typeof vuela);
console.log('Maneja', maneja);
console.log('Maneja', typeof maneja);
console.log('Vida', vida);
console.log('Vida', typeof vida);
console.log('Trabajo', trabajo);
console.log('Trabajo', typeof trabajo);
console.log('Tiempo libre', tiempoLibre);
console.log('Tiempor libre', typeof tiempoLibre);
